config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'users/index'

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  get 'profiles/index'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'learn' => 'static_pages#learn'

  devise_for :users, controllers: { registrations: 'registrations',
                                    sessions: 'sessions',
                                    passwords: 'passwords',
                                    unlocks: 'unlocks',
                                    confirmations: 'confirmations' }

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :comments
  end

  resources :posts do
    resources :comments do
      resources :responses
    end
  end

  resources :posts do
    member do
      put 'like',   to: 'posts#like'
      put 'dislike', to: 'posts#dislike'
      put 'unlike',   to: 'posts#unlike'
    end
  end
  resources :posts do
    resources :comments do
      member do
        put 'like',   to: 'comments#like'
        put 'dislike', to: 'comments#dislike'
        put 'unlike',   to: 'comments#unlike'
      end
    end
  end

  resources :comments do
    resources :responses do
      member do
        put 'like',   to: 'responses#like'
        put 'dislike', to: 'responses#dislike'
        put 'unlike',   to: 'responses#unlike'
      end
    end
  end

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :profile_owner, only: [:edit, :update]
  before_action :count_tags
  before_action :verify_confirmed



  def index
    @users = User.all
  end

  def show
    @posts = @user.posts.order('created_at DESC')
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def verify_confirmed
      unless current_user.confirmed?
        flash[:alert] = "Please confirm your email first"
        redirect_to :back
      end
    end

  def profile_params
    params.require(:user).permit(:avatar, :bio, :occupation)
  end

  def profile_owner
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

  def count_tags
      @tag_counts = Post.where("created_at > ?", Time.now - 5.days).tag_counts_on(:tags)
                      .order('count desc')
                      .limit(10)
    end

  def follow_25

  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_avatar_select(user)
    return image_tag user.avatar.url(:medium),
                     class: 'profile-image' if user.avatar.exists?
    image_tag 'blank_profile_pic.png',
                                    class: 'profile-image'
  end

  def index_profile_avatar_select(user)
    return image_tag user.avatar.url(:thumb),
                     class: 'index-profile-image' if user.avatar.exists?
    image_tag 'blank_profile_pic.png',
                                    class: 'index-profile-image'
  end

  def show_profile_avatar_select(user)
    return image_tag user.avatar.url(:thumb),
                     class: 'index-profile-image' if user.avatar.exists?
    image_tag 'blank_profile_pic.png',
                                    class: 'show-profile-image'
  end

  def comment_profile_avatar_select(user)
    return image_tag user.avatar.url(:thumb),
                     class: 'comment-profile-image' if user.avatar.exists?
    image_tag 'blank_profile_pic.png',
                                    class: 'comment-profile-image'
  end

  def reply_profile_avatar_select(user)
    return image_tag user.avatar.url(:thumb),
                     class: 'reply-profile-image' if user.avatar.exists?
    image_tag 'blank_profile_pic.png',
                                    class: 'reply-profile-image'
  end

  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end

  def followers_grammar(user)
    user.followers.count == 1 ? " follower" : " followers"
  end



end

app/views/profiles/_comment_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, comment.user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/profiles/_comment_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: comment.user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/profiles/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/profiles/_follow_form.html.haml
-unless @user == current_user
  #follow_form
    -if current_user.following?(@user)
      = render 'unfollow'
    -else
      = render 'follow'

app/views/profiles/_follow_unfollow.html.haml
- if current_user_is_following(current_user.id, @user.id)
  = link_to 'Following', unfollow_user_path,
                           remote: true,
                           class: 'btn unfollow-button',
                           id: 'unfollow-button',
                           method: :post
- else
  = link_to 'Follow', follow_user_path,
                        remote: true,
                        class: 'btn follow-button',
                        id: 'follow-button',
                        method: :post

app/views/profiles/_post_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @post.user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/profiles/_post_follow_form.html.haml
-unless @post.user == current_user
  #follow_form
    -if current_user.following?(@post.user)
      = render 'profiles/post_unfollow'
    -else
      = render 'profiles/post_follow'

app/views/profiles/_post_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @post.user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/profiles/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/profiles/edit.html.haml
%br
.container-fluid.edit_profile_page
  = simple_form_for @user, url: {action: "update"}, html: { multipart: true } do |f|
    #edit_profile_pic
      = profile_avatar_select(@user)
    %h4 Change your profile image:
    = f.input :avatar, onChange: 'loadFile(event)', label:false
    %br
    %br
    %br
    = f.input :occupation, label: "What's your occupation? (20 characters maximum)", maxlength: 20
    = f.input :bio, label: "Add a bio to display on your profile page"

    = f.submit "Update Profile", class: 'btn btn-success'

app/views/profiles/show.html.haml
.container-fluid.profile_container
  .posts-wrapper
    %br
    -if current_user == @user
      %h4
        =link_to "Edit Profile", edit_profile_path
    %div{ :class => follow_num(@user) }= profile_avatar_select(@user)

  .profile_basic_content

    %h3.profile_user_name
      = @user.user_name
    %p
      = @user.occupation
    %span= render 'shared/stats'
    %span.profile_follow_form= render 'follow_form'
  %br
  .profile-bio
    = simple_format(@user.bio)
.container.organize_rows#my-posts
  = render @posts