config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'users/index'

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  get 'profiles/index'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'learn' => 'static_pages#learn'

  devise_for :users, controllers: { registrations: 'registrations',
                                    sessions: 'sessions',
                                    passwords: 'passwords',
                                    unlocks: 'unlocks',
                                    confirmations: 'confirmations' }

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :comments
  end

  resources :posts do
    resources :comments do
      resources :responses
    end
  end

  resources :posts do
    member do
      put 'like',   to: 'posts#like'
      put 'dislike', to: 'posts#dislike'
      put 'unlike',   to: 'posts#unlike'
    end
  end
  resources :posts do
    resources :comments do
      member do
        put 'like',   to: 'comments#like'
        put 'dislike', to: 'comments#dislike'
        put 'unlike',   to: 'comments#unlike'
      end
    end
  end

  resources :comments do
    resources :responses do
      member do
        put 'like',   to: 'responses#like'
        put 'dislike', to: 'responses#dislike'
        put 'unlike',   to: 'responses#unlike'
      end
    end
  end

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_votable
  scope :of_followed_users, -> (following_users) { where user_id: following_users }

  validates :content, presence: true, length: { minimum: 10 }
  belongs_to :user
  belongs_to :post
  has_many :notifications, dependent: :destroy
  has_many :responses, dependent: :destroy
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_confirmed
  before_action :set_post
  before_action :owned_comment, only: [:edit, :update, :destroy]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      create_notification @post, @comment
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = 'Check the comment form, something went wrong.'
    end
  end



  def destroy
    @comment = @post.comments.find(params[:id])
    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to :back}
        format.js
      end
    end
  end

  def like
    @comment = @post.comments.find(params[:id])
    @comment.upvote_by current_user
    respond_to do |format|
      format.js { render "comment_dislike.js.erb" }
    end
    create_upvote_notification @post, @comment

  end

  def dislike
    @comment = @post.comments.find(params[:id])
    @comment.downvote_by current_user
    respond_to do |format|
      format.js { render "comment_dislike.js.erb" }
    end

  end

  def unlike
    @comment = @post.comments.find(params[:id])
    @comment.unvote_by current_user
    respond_to do |format|
      format.js { render "comment_dislike.js.erb" }
    end
  end



  private

    def verify_confirmed
      unless current_user.confirmed?
        flash[:alert] = "Please confirm your email first"
        redirect_to :back
      end
    end

    def create_notification(post, comment)
    return if comment.user.id == current_user.id
    Notification.create(user_id: post.user.id,
                        notified_by_id: current_user.id,
                        post_id: post.id,
                        identifier: comment.id,
                        notice_type: 'commented on your post')
    end



    def create_upvote_notification(post, comment)
      return if comment.user.id == current_user.id
      Notification.create(user_id: comment.user.id,
                          notified_by_id: current_user.id,
                          post_id: post.id,
                          identifier: comment.id,
                          notice_type: 'likes your comment')
    end




    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_post
    @post = Post.find(params[:post_id])
    end

    def owned_comment
      unless current_user == @post.user
        flash[:alert] = "That post doesn't belong to you!"
        redirect_to root_path
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper

  def comment_count
    case @post.comments.count
    when 0
      return "Be the first to comment."
    when 1
      return "There is 1 comment so far."
    else
       "There are " +  @post.comments.count.to_s + " comments so far."
    end
  end

  def comment_count_index(post)
    case post.comments.count
    when 0
      return "Be the first to comment."
    when 1
      return "1 comment"
    else
      post.comments.count.to_s + " comments"
    end
  end

  def likers_of(comment)
    votes = comment.votes_for.up.by_type(User)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def liked_comment(comment)
    return 'glyphicon-liked' if current_user.voted_for? comment
    'glyphicon-unliked'
  end

  private

  def like_plural(votes)
    return ' likes this'
  end

  def dislike_plural(votes)
    return ' dislikes this'
  end

  def display_comment_likes(comment)
    votes = comment.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
    count_likers(votes)
  end

  def display_comment_dislikes(comment)
    votes = comment.votes_for.down.by_type(User)
    return list_dislikers(votes) if votes.size <= 8
    count_dislikers(votes)
  end

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def list_dislikers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + dislike_plural(votes)
    end
  end

end

app/views/comments/_comment.html.haml
.first_comment_format{id: "comment_response_block_#{comment.id}"}
  %strong
    - if user_signed_in?
      %span{ :class => follow_num(comment.user) }=link_to comment_profile_avatar_select(comment.user), profile_path(comment.user.user_name)
    -else
      %span{ :class => follow_num(comment.user) }=comment_profile_avatar_select(comment.user)
  -if user_signed_in?
    %strong.comment_user_name= render 'posts/user_info', post: comment
    %br
    = simple_format(comment.content)
    - if comment.user == current_user || current_user.admin
      = link_to post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?"}, remote: true, id: "delete-#{comment.id}" do
        .glyphicon.glyphicon-remove
  -else
    %strong.comment_user_name= render 'posts/so_user_info', post: comment
    %br
    = simple_format(comment.content)
  %span= render 'comments/likes', post: @post, comment: comment
  -if comment.responses.any?
    .container.reply_container
      .responses{id: "responses_#{comment.id}"}
        - if user_signed_in?
          = render comment.responses, post: @post, comment: comment
        -else
          = render comment.responses, post: @post, comment: comment
  -if user_signed_in?
    = render 'responses/form', comment: comment
  -if !user_signed_in? && comment.responses.count > 0
    .signed_out_reply_line
  -unless user_signed_in? || comment.responses.count > 0
    %br

app/views/comments/_followed_users.html.haml
.first_comment_format
  %span{ :class => follow_num(comment.user) }=link_to comment_profile_avatar_select(comment.user), profile_path(comment.user.user_name)
  %strong.comment_user_name= render 'posts/user_info', post: comment
  .comment_time_ago #{time_ago_in_words comment.created_at} ago
  = simple_format(comment.content)
  %span.voter_names= render 'comments/likes', comment: comment

app/views/comments/_likes.html.haml
.comment_votes{id: "comment_votes_#{comment.id}"}
  .likes.voter_names{id: "likes_#{comment.id}"}
    = display_likes comment
  .dislikes.voter_names{id: "dislikes_#{comment.id}"}
    = display_dislikes comment
  -if user_signed_in? && current_user != comment.user
    - unless current_user.voted_up_on? comment
      =link_to like_post_comment_path(@post, comment), remote: true, id: "likes_#{comment.id}", method: :put do
        %span.glyphicon.glyphicon-thumbs-up
    - else
      =link_to unlike_post_comment_path(@post, comment), remote: true, id: "likes_#{comment.id}", method: :put do
        %span.glyphicon.glyphicon-thumbs-up.glyphicon-selected
    - unless current_user.voted_down_on? comment
      =link_to dislike_post_comment_path(@post, comment), remote: true, id: "likes_#{comment.id}", method: :put do
        %span.glyphicon.glyphicon-thumbs-down
    - else
      =link_to unlike_post_comment_path(@post, comment), remote: true, id: "likes_#{comment.id}", method: :put do
        %span.glyphicon.glyphicon-thumbs-down.glyphicon-selected
  %span.comment_time_ago #{time_ago_in_words comment.created_at} ago

app/views/comments/comment_dislike.js.erb
$("#comment_votes_<%= @comment.id %> ").html("<%= j (render partial: 'comments/likes', locals: { comment: @comment} ) %>");

app/views/comments/comment_like.js.erb
$("#comment_votes_<%= @comment.id %> ").html("<%= j (render partial: 'comments/likes', locals: { comment: @comment} ) %>");

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");