config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'users/index'

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  get 'profiles/index'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'learn' => 'static_pages#learn'

  devise_for :users, controllers: { registrations: 'registrations',
                                    sessions: 'sessions',
                                    passwords: 'passwords',
                                    unlocks: 'unlocks',
                                    confirmations: 'confirmations' }

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :comments
  end

  resources :posts do
    resources :comments do
      resources :responses
    end
  end

  resources :posts do
    member do
      put 'like',   to: 'posts#like'
      put 'dislike', to: 'posts#dislike'
      put 'unlike',   to: 'posts#unlike'
    end
  end
  resources :posts do
    resources :comments do
      member do
        put 'like',   to: 'comments#like'
        put 'dislike', to: 'comments#dislike'
        put 'unlike',   to: 'comments#unlike'
      end
    end
  end

  resources :comments do
    resources :responses do
      member do
        put 'like',   to: 'responses#like'
        put 'dislike', to: 'responses#dislike'
        put 'unlike',   to: 'responses#unlike'
      end
    end
  end

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  acts_as_taggable_on :tags
  ActsAsTaggableOn.default_parser = MyParser
  scope :of_followed_users, -> (following_users) { where user_id: following_users }
  #before_save :ends_with_q
  before_save :get_image_from_link,
              if: ->(post) { post.link_changed? }
  VALID_LINK_REGEX = /\Ahttp\.*/
  validates :link,  presence: true, format: { with: VALID_LINK_REGEX }
  validates :commentary, presence: true
  validates :user_id, presence: true
  validates :tag_list, presence: true, length: { maximum: 30}
  belongs_to :user
  has_many :comments,      dependent: :destroy
  has_many :responses,     dependent: :destroy
  has_many :notifications, dependent: :destroy
  #validates :image_link, presence: true
  has_attached_file :image, styles: { medium: "260x", thumb: "100x"},
                         default_url: 'https://s31.postimg.org/z6185cysb/question_mark.jpg'
  validates_attachment_content_type :image,
                                     content_type: /\Aimage\/.*\Z/

  def self.search(query)
    joins(:user).where("lower(commentary) LIKE :search OR lower(link) LIKE :search OR lower(users.user_name) LIKE :search", search: "%#{query.downcase}%")
  end

  #def ends_with_q
   # return if self.title.empty?
   # self.title = (/\A.*\?\z/).match(self.title).nil? ? title.strip + "?" : title.strip
  #end

  private

        def get_image_from_link
          page = MetaInspector.new(link)
          self.image_link = page.images.best.present? ? page.images.best : "https://s32.postimg.org/7wdmzydut/hintergrund_tapete_1460040441_Mp1.jpg"
        end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy, :edit, :update, :like, :dislike, :unlike]
  before_action :verify_confirmed, only: [:new, :create, :delete, :like, :dislike, :edit, :update]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like, :dislike, :unlike]
  before_action :owned_post, only: [:edit, :update, :destroy]
  before_action :count_tags


  def index
    if user_signed_in?
      @posts = Post.paginate(page: params[:page], per_page: 36)
                 .where("created_at > ?", Time.now - 5.days)
                 .order(cached_votes_up: :desc)
    else
      if Post.count > 20
      @posts = Post.paginate(page: params[:page], per_page: 36)
                 .where("created_at > ?", Time.now - 5.days)
                 .order(cached_votes_up: :desc)
      else
      @posts = nil
      end
    end
      if params[:search]
        @posts = Post.paginate(page: params[:page], per_page: 36)
                 .search(params[:search]).order("created_at DESC")
      elsif params[:tag]
        @posts = Post.paginate(page: params[:page], per_page: 36)
                     .tagged_with(params[:tag])
                     .order(cached_votes_up: :desc)
      end


  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    current_user.posts << @post
    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash.now[:alert] = "Uh oh! Something went wrong. Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    @post.update(update_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  def like
    @post.upvote_by current_user
    respond_to do |format|
      format.js { render "like.js.erb" }
    end
    create_upvote_notification @post

  end

  def dislike
    @post.downvote_by current_user
    respond_to do |format|
      format.js { render "dislike.js.erb" }
    end
  #  create_downvote_notification @post
  end

  def unlike
    @post.unvote_by current_user
    respond_to do |format|
      format.js { render "dislike.js.erb"}

    end
  end

  def more_posts
    Post.paginate(page: params[:page], per_page: 12).order(cached_weighted_total: :desc)
  end

  private

    def verify_confirmed
      unless current_user.confirmed?
        flash[:alert] = "Please confirm your email first"
        redirect_to :back
      end
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:link, :image, :commentary, :tag_list, :image_link)
    end

    def update_params
      params.require(:post).permit(:image, :commentary)
    end

    def owned_post
      unless current_user == @post.user
        flash[:alert] = "That post doesn't belong to you!"
        redirect_to root_path
      end
    end

    def create_upvote_notification(post)
    return if post.user.id == current_user.id
    Notification.create(user_id: post.user.id,
                        notified_by_id: current_user.id,
                        post_id: post.id,
                        identifier: post.id,
                        notice_type: 'likes your post')
    end

    def count_tags
      @tag_counts = Post.where("created_at > ?", Time.now - 5.days).tag_counts_on(:tags)
                      .order('count desc')
                      .limit(10)
    end

end

app/helpers/posts_helper.rb
module PostsHelper



  def index_commentary_shrink(str)
    str.gsub("<br>", " ")
     .gsub(/<img.+>/, "")
     .gsub('a target="_blank" rel="nofollow" href="', "")
     .gsub('<\a>', "")
     .split("").length > 150 ?
    str.split("")[0...150].join("") + "..." : str
  end

  def likers_of(post)
    votes = post.votes_for.up.by_type(User)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + like_plural(votes)
    end
  end

  def liked_post(post)
    return 'glyphicon-liked' if current_user.voted_for? post
    'glyphicon-unliked'
  end

  private

  def post_like_plural(votes)
    return ' likes this'
  end

  def post_dislike_plural(votes)
    return ' dislikes this'
  end

  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 4
    count_likers(votes)
  end

  def display_dislikes(post)
    votes = post.votes_for.down.by_type(User)
    return list_dislikers(votes) if votes.size <= 4
    count_dislikers(votes)
  end

  def list_likers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + post_like_plural(votes)
    end
  end

  def list_dislikers(votes)
    user_names = []
    unless votes.blank?
      votes.voters.each do |voter|
        user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
      user_names.to_sentence.html_safe + post_dislike_plural(votes)
    end
  end

  def count_likers(votes)
    user_names = []
    votes.voters.take(2).each do |voter|
      user_names.push(link_to voter.user_name,
                                profile_path(voter.user_name),
                                class: 'user-name')
      end
    "#{user_names.first}, #{user_names.last} and #{votes.size - 2} others like this".html_safe
  end

  def like_plural(votes)
    return ' like this' if votes.count > 1
    ' likes this'
  end

  def count_dislikers(votes)
    vote_count = votes.size
    (vote_count - 2).to_s + ' others dislike this'
  end

  def dislike_plural(votes)
    return ' dislike this' if votes.count > 1
    ' dislikes this'
  end


end

app/views/posts/_all_posts.html.haml
- if user_signed_in?
  - @all_posts = Post.paginate(page: params[:page], per_page: 36).order(created_at: :desc) - Post.paginate(page: params[:page], per_page: 36).of_followed_users(current_user.following).where("created_at > ?", Time.now - 5.days)
-else
  - @all_posts = Post.paginate(page: params[:page], per_page: 36).order(created_at: :desc)
- @all_posts.each do |post|
  .item
    .well
      -if user_signed_in?
        %span{ :class => follow_num(post.user) }= link_to (index_profile_avatar_select(post.user)), profile_path(post.user.user_name), method: :get
        %strong.index_bio_capsule.index_name= render 'posts/user_info', post: post
      -else
        %span{ :class => follow_num(post.user) }= index_profile_avatar_select(post.user)
        %strong.index_bio_capsule.index_name= render 'posts/so_user_info', post: post
      %span.index_time_ago=time_ago_in_words post.created_at
      = link_to post.link do
        - unless post.image.present?
          %span.post_image=image_tag post.image_link
        - else
          %span.post_image= image_tag post.image
        .image_link_divider
        .small_font.index_post_link
          = post.link
        %hr
      = link_to post_path(post), method: :get do
        %h5=simple_format(index_commentary_shrink(post.commentary))
        .small_font= comment_count_index(post)
      %hr
      -if post.tags.count == 1
        %span Tag:
      -else
        %span Tags:
      %span=raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(", ")

app/views/posts/_edit_form.html.haml
= simple_form_for @post do |f|
  = f.input  :image, label: "Unhappy with the pic we chose for you? Upload your own."
  = f.bootsy_area  :commentary, placeholder: 'Type type type...', class: 'form-control'
  = f.input  :tag_list
  = f.button :submit

app/views/posts/_likes.html.haml
#votes_up_down
  .likes.voter_names{id: "likes_#{@post.id}"}
    = display_likes @post
  .dislikes.voter_names{id: "dislikes_#{@post.id}"}
    = display_dislikes @post
  -if user_signed_in? && current_user != @post.user
    - unless current_user.voted_up_on? @post
      =link_to like_post_path(@post), remote: true, id: "likes_#{@post.id}", method: :put do
        %span.glyphicon.glyphicon-thumbs-up
    - else
      =link_to unlike_post_path(@post), remote: true, id: "likes_#{@post.id}", method: :put do
        %span.glyphicon.glyphicon-thumbs-up.glyphicon-selected
    - unless current_user.voted_down_on? @post
      =link_to dislike_post_path(@post), remote: true, id: "likes_#{@post.id}", method: :put do
        %span.glyphicon.glyphicon-thumbs-down
    - else
      =link_to unlike_post_path(@post), remote: true, id: "likes_#{@post.id}", method: :put do
        %span.glyphicon.glyphicon-thumbs-down.glyphicon-selected

app/views/posts/_new_form.html.haml
= simple_form_for @post do |f|
  = f.input  :link, hint: "(Required) Make sure it includes 'http://' or 'https://' at the beginning."
  %strong Add your commentary here
  = f.bootsy_area  :commentary, hint: "(Required) Add your own thoughts, commentary here:", placeholder: 'Type type type...', class: 'form-control'
  = f.input  :tag_list, label: "Tags", hint: "(Required) Use commas or spaces to separate", maxlength: 30
  = f.input  :image, label: "Thread pic", hint: "(Optional) Upload an image to accompany your post in the news feed. If you don't, we'll find a pic for you that you can change at any time."
  = f.button :submit

app/views/posts/_popular_posts.html.haml
.popular_posts
  Trending:
  - @tag_counts.each do |tag|
    = link_to tag, tag_path(tag.name)

app/views/posts/_post.html.haml
.item
  .well
    %span{ :class => follow_num(post.user) }= link_to (index_profile_avatar_select(post.user)), profile_path(post.user.user_name), method: :get
    -if user_signed_in?
      %strong.index_bio_capsule.index_name= render 'posts/user_info', post: post
    -else
      %strong.index_bio_capsule.index_name= render 'posts/so_user_info', post: post
    %span.index_time_ago=time_ago_in_words post.created_at
    = link_to post.link do
      - unless post.image.present?
        %span.post_image=image_tag post.image_link
      - else
        %span.post_image= image_tag post.image
      .image_link_divider
      .small_font.index_post_link
        = post.link
      %hr
    = link_to post_path(post), method: :get do
      %h5=simple_format(index_commentary_shrink(post.commentary))
      .small_font= comment_count_index(post)
    %hr
    -if post.tags.count == 1
      %span Tag:
    -else
      %span Tags:
    %span=raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(", ")

app/views/posts/_so_user_info.html.erb
<span data-html="true" data-toggle="tooltip" data-placement="right" title="<%= post.user.occupation %>"><%= post.user.user_name %></span>

app/views/posts/_user_info.html.erb
<span data-html="true" data-toggle="tooltip" data-placement="right" title="<%= post.user.occupation %>"><%= link_to post.user.user_name, profile_path(post.user.user_name) %></span>

app/views/posts/dislike.js.erb
$("#votes_up_down").replaceWith("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/edit.html.haml
.new_post_format
  %br
  = link_to 'Back to post', @post
  %h1 Edit Post
  = render 'edit_form'

app/views/posts/index.html.haml
.nav_decoy
.container.organize_rows#my-posts
  -begin
    = render @posts
  -rescue ArgumentError
  - unless params[:tag] || params[:search]
    = render 'all_posts', post: @post

#infinite-scrolling
  -begin
    = will_paginate
  -rescue ArgumentError

app/views/posts/like.js.erb
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.haml
.new_post_format
  %h1 New Thread
  %p.new_post_grey Share an article, video, whatever has a link but isn't just a picture, to start a thread.
  = render 'new_form'

app/views/posts/show.html.haml
.comment_format.post_head
  -if user_signed_in?
    - if @post.tag_list.count == 1
      Tag:
    - else
      Tags:
    %span
      = raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(", ")
    %hr.show_hr
    .show_tag_divider
  - if user_signed_in?
    %span{ :class => follow_num(@post.user) }= link_to index_profile_avatar_select(@post.user), profile_path(@post.user.user_name)
    %span.show_signed_in_name
      = render 'user_info', post: @post
    %br
    .small_font posted this #{time_ago_in_words @post.created_at} ago
    .follow_divider
    = render 'profiles/post_follow_form'
  - else
    %br
    %span{ :class => follow_num(@post.user) }= index_profile_avatar_select(@post.user)
    %li.signed_out_names
      = render 'so_user_info', post: @post
    %br
    .small_font posted this #{time_ago_in_words @post.created_at} ago
  - begin
    - if @post.user.id == current_user.id || current_user.admin == true
      = link_to edit_post_path(@post) do
        %span.glyphicon.glyphicon-wrench{"data-placement" => "top", "data-toggle" => "tooltip", :title => "Edit post", :type => "button"}
      = link_to post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } do
        %span.glyphicon.glyphicon-trash{"data-placement" => "top", "data-toggle" => "tooltip", :title => "Delete post", :type => "button"}
    %br
  - rescue NoMethodError
  %br


  = link_to '', "https://www.facebook.com/dialog/share?app_id=625876907589354&href=#{request.original_url}&redirect_uri=#{request.original_url}", class: " btn btn-facebook"
  = link_to '', "https://www.facebook.com/dialog/share?app_id=625876907589354&href=#{request.original_url}&redirect_uri=#{request.original_url}", class: "fa fa-facebook"

  = link_to "", "http://twitter.com/home?status=#{post_url(@post)}", class: "fa fa-twitter btn btn-twitter"
  %br
  %br



  %li= simple_format(@post.commentary.strip)
  %span= render 'posts/likes'
  .show_post_link= link_to @post.link, @post.link
  - if @post.comments.any?
    %hr.show_divider
  - else
    %br


.comment_format
  .comments{id: "comments_#{@post.id}"}
    - if @post.comments.any?
      -if user_signed_in?
        - @followerposts = @post.comments.of_followed_users(current_user.following).order(cached_votes_score: :desc)
        - @unfollowedposts = @post.comments.order(cached_votes_score: :desc) - @post.comments.of_followed_users(current_user.following)
        - @result = @followerposts + @unfollowedposts
        = render @result, post: @post
      -else
        = render @post.comments.order(cached_votes_score: :desc), post: @post
- if user_signed_in?
  .comment_format
    = simple_form_for([@post, @post.comments.build], remote: true)  do |f|
      = f.input :content, label:'Add your commentary:', hint: '10 characters minimum'
      = f.submit "Submit", class: "btn btn-default", error: "10 chars min."