config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  get 'users/index'

  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'
  get 'profiles/show'
  get 'profiles/index'
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'learn' => 'static_pages#learn'

  devise_for :users, controllers: { registrations: 'registrations',
                                    sessions: 'sessions',
                                    passwords: 'passwords',
                                    unlocks: 'unlocks',
                                    confirmations: 'confirmations' }

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :posts do
    resources :comments
  end

  resources :posts do
    resources :comments do
      resources :responses
    end
  end

  resources :posts do
    member do
      put 'like',   to: 'posts#like'
      put 'dislike', to: 'posts#dislike'
      put 'unlike',   to: 'posts#unlike'
    end
  end
  resources :posts do
    resources :comments do
      member do
        put 'like',   to: 'comments#like'
        put 'dislike', to: 'comments#dislike'
        put 'unlike',   to: 'comments#unlike'
      end
    end
  end

  resources :comments do
    resources :responses do
      member do
        put 'like',   to: 'responses#like'
        put 'dislike', to: 'responses#dislike'
        put 'unlike',   to: 'responses#unlike'
      end
    end
  end

  get ':user_name', to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/views/layouts/_flashes.html.haml
.container
  -flash.each do |name, msg|
    = content_tag :div, msg, class: [:alert, alert_for(name)]

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    = link_to 'thredbed', '/', class:"navbar-brand", method: :get
    %span.glyphicon.glyphicon-cloud
  / Collect the nav links, forms, and other content for toggling
  #bs-example-navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li=link_to 'home', '/', method: :get
      %li= link_to 'learn more', learn_path
      %li.dropdown
        %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          trending
          %span.caret
        %ul.dropdown-menu
          - @tag_counts.each do |tag|
            %li= link_to tag, tag_path(tag.name)
    .navbar-form.navbar-left
      .form-group
        =form_tag(posts_path, method: :get) do
          %span= text_field_tag :search, params[:search], placeholder: "Search posts, users, URLs", class: "form-control"
          %button.btn.btn-default{:type => "submit"} Go
    -if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li.notifications_count
          = new_notifs(current_user)
        %li.dropdown
          %a.notif_dropdown.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %span.glyphicon.glyphicon-globe
          %ul.dropdown-menu.notifications-dropdown-menu
            %li.dropdown-header Notifications
            %hr
            = render current_user.notifications.order('created_at DESC').where(read: false).take(5)
            %li.text-center= link_to 'View All', notifications_path
        %li
          = link_to 'New thread', new_post_path, method: :get

        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            = current_user.user_name
            %span.caret
          %ul.dropdown-menu
            %li
              %li= link_to "Profile", profile_path(current_user.user_name)
            %li
              %li= link_to "Settings", edit_user_registration_path
            %li.divider{:role => "separator"}
            %li
              %li= link_to 'Sign out', destroy_user_session_path, method: :delete
    - else
      %ul.nav.navbar-nav.navbar-right
        - unless user_signed_in? && ( !current_page?(new_user_registration_path) || !current_page?(new_user_session_path) )
          %li.login_or_signup_to
            %span.sign_up_underline= link_to 'Login',  new_user_session_path
            or
            %span.sign_up_underline= link_to "Sign up", new_user_registration_path
            to post or comment.


  / /.navbar-collapse
/ /.container-fluid

app/views/layouts/_popular_tags.html.haml
.popular_posts
  Trending:
  - @tag_counts.each do |tag|
    = link_to tag, tag_path(tag.name)

app/views/layouts/_trending.html.erb
<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Tooltip on bottom">Tooltip on bottom</button>

app/views/layouts/application.html.haml
%html
  %head
    %title=notif_title_count
    %meta{:charset => "utf-8"}
    %meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    %script{:src => "https://www.google.com/recaptcha/api.js"}
    = csrf_meta_tags
%body

  = render 'layouts/navbar'
  .nav_decoy
  = render 'layouts/flashes'
  = yield